/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imagesdownloader;

import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.ListModel;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author Borys
 */
public class simpleGui extends javax.swing.JFrame {
    
    public ArrayList<URL> links;
    public ArrayList<URL> mediaLinks;
    /**
     * Creates new form simpleGui
     */
    public simpleGui() {
        initComponents();
        links = new ArrayList<>();
        mediaLinks = new ArrayList<>();
        DefaultListModel model = new DefaultListModel();
        addressList.setModel(model);
        JMenuBar bar = createMenuBar();
        workingPanel.add(bar,BorderLayout.BEFORE_FIRST_LINE);
        workingPanel.revalidate();
        workingPanel.repaint();
        
//        addressList.setVisibleRowCount(2);
        jScrollPane1.setViewportView(addressList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workingPanel = new javax.swing.JPanel();
        mediaAddress = new javax.swing.JTextField();
        addMedia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressList = new javax.swing.JList();
        clearList = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workingPanel.setLayout(new java.awt.BorderLayout());
        workingPanel.add(mediaAddress, java.awt.BorderLayout.CENTER);

        addMedia.setText("Add/Download");
        addMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMediaActionPerformed(evt);
            }
        });
        workingPanel.add(addMedia, java.awt.BorderLayout.LINE_END);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setAutoscrolls(true);

        addressList.setToolTipText("");
        addressList.setMaximumSize(new java.awt.Dimension(50, 85));
        addressList.setMinimumSize(new java.awt.Dimension(50, 85));
        addressList.setPreferredSize(new java.awt.Dimension(50, 85));
        addressList.setSize(new java.awt.Dimension(60, 56));
        addressList.setVisibleRowCount(10);
        jScrollPane1.setViewportView(addressList);

        workingPanel.add(jScrollPane1, java.awt.BorderLayout.PAGE_END);

        clearList.setText("Clear list");
        clearList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearListActionPerformed(evt);
            }
        });
        workingPanel.add(clearList, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMediaActionPerformed
        String urlStr = mediaAddress.getText();
        if(!urlStr.equals("")){
            try {
                URL singleUrl = new URL(urlStr);
                links.add(singleUrl);
                DefaultListModel model = (DefaultListModel) addressList.getModel();
                model.addElement(singleUrl);
                addressList.repaint();
                mediaAddress.setText("");
            } catch (MalformedURLException ex) {
                Logger.getLogger(simpleGui.class.getName()).log(Level.SEVERE, null, ex);
                mediaAddress.setText("WRONG URL");
            }
        }
        else if(urlStr.equals("")){
            try {
                if(links.size()>0){
                    mediaAddress.setText("Downloading!");
                    BasicConnection connection = new BasicConnection(1);
                    connection.Download(links,mediaLinks);
                    mediaAddress.setText("Items were downloaded!");
                }
                else{
                    mediaAddress.setText("Nothing to download!");
                }
            } catch (IOException ex) {
                Logger.getLogger(simpleGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addMediaActionPerformed

    private void clearListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearListActionPerformed
        DefaultListModel model = (DefaultListModel) addressList.getModel();
        model.removeAllElements();
        links.removeAll(links);
        mediaLinks.removeAll(mediaLinks);
        mediaAddress.setText("");
        addressList.repaint();
    }//GEN-LAST:event_clearListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(simpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(simpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(simpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(simpleGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new simpleGui().setVisible(true);
            }
        });
    }
    public JMenuBar createMenuBar () {
        JMenuItem menuItem = null;
        JMenuBar menuBar = new JMenuBar();
        JMenu mainMenu = new JMenu("Edit");
        mainMenu.setMnemonic(KeyEvent.VK_E);

        menuItem = new JMenuItem(new DefaultEditorKit.CutAction());
        menuItem.setText("Cut");
        menuItem.setMnemonic(KeyEvent.VK_T);
        mainMenu.add(menuItem);

        menuItem = new JMenuItem(new DefaultEditorKit.CopyAction());
        menuItem.setText("Copy");
        menuItem.setMnemonic(KeyEvent.VK_C);
        mainMenu.add(menuItem);

        menuItem = new JMenuItem(new DefaultEditorKit.PasteAction());
        menuItem.setText("Paste");
        menuItem.setMnemonic(KeyEvent.VK_P);
        mainMenu.add(menuItem);

        menuBar.add(mainMenu);
        return menuBar;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedia;
    private javax.swing.JList addressList;
    private javax.swing.JButton clearList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mediaAddress;
    private javax.swing.JPanel workingPanel;
    // End of variables declaration//GEN-END:variables
}
